apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  serviceAccountName: cicd-jenkins
  containers:
    - name: helm
      image: alpine/helm:2.13.1
      command:
        - cat
      tty: true
    - name: jnlp
      image: jenkins/jnlp-slave:3.27-1
      imagePullPolicy: Always
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP